# Site settings
title: ANYUANDESIGN
header-img: "img/autumn2.jpg"
tagline: "吉光片羽"
description: "心之所向 居之所在"
baseurl: ""
url: "http://anyuandesign.com"
#url: "http://localhost:4000"

# About/contact
owner:
  name: "unfly"
  email: unflys@gmail.com
  bio: "心之所向 居之所在bio"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: unfly
twitter_username: unfly
github_username: unfly
facebook_username: unfly
weibo_username: unfly
zhihu_username: unfly

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems:
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Azeril"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments
comments :
  provider : duoshuo
  duoshuo :
    short_name : unfly
  disqus :
      short_name : unfly

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
