# Site settings
title: 安源室內設計事務所
header-img: img/home-bg.jpg
email: luan345826@hotmail.com
copyright_name: Your/Project/安源室內設計事務所
description: "设计的本质是以人为中心，提供自然舒适的居住环境，为居住者提供完全无拘无束的自在空间。"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://yourdomain.com"
twitter_username: anyuan
github_username:  anyuan
facebook_username:  anyuan
email_username:  anyuan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
